[common]
bind_port = 32987
bind_udp_port = 32988
token = "anquan1st"

vhost_http_port = 32989
dashboard_port = 32990

# console or real logFile path like ./frps.log
log_file = "./frps.log"

# trace, debug, info, warn, error
log_level = "info"

log_max_days = 3

# disable log colors when log_file is console, default is false
disable_log_color = false
