# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: App
on:
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "main","master" ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub #登陆docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  #docker的用户名
          password: ${{ secrets.DOCKER_PASSWORD }}    #docker的密码
      - name: Build and push Docker image  #构建和发布 docker镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frp-server:latest
      - name: copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_IP }} #云服务器的ip
          username: ${{ secrets.SSH_USERNAME }} #云服务器的用户名
          password: ${{ secrets.SSH_PASSWORD }} #云服务器的密码
          port: ${{ secrets.SSH_PORT }}
          source: docker-compose.yml
          overwrite: true
          target: ./frp-server
      - name: deploy image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_IP }} #云服务器的ip
          username: ${{ secrets.SSH_USERNAME }} #云服务器的用户名
          password: ${{ secrets.SSH_PASSWORD }} #云服务器的密码
          script: |
            cd frp-server
            docker pull ${{ secrets.DOCKER_USERNAME }}/frp-server:latest
            docker-compose pull
            docker image prune -f
            docker-compose up -d
